# Getting Financial Data - Pandas Datareader

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

# package to extract data from various Internet sources into a DataFrame
# make sure you have it installed
import pandas_datareader.data as web

# package for dates
import datetime as dt

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is).

In [2]:
from datetime import datetime

start = datetime.strptime('2015-01-01', '%Y-%m-%d')
end = datetime.today()

### Step 3. Get an API key for one of the APIs that are supported by Pandas Datareader, preferably for AlphaVantage.

If you do not have an API key for any of the supported APIs, it is easiest to get one for [AlphaVantage](https://www.alphavantage.co/support/#api-key). (Note that the API key is shown directly after the signup. You do *not* receive it via e-mail.)

(For a full list of the APIs that are supported by Pandas Datareader, [see here](https://pydata.github.io/pandas-datareader/readers/index.html). As the APIs are provided by third parties, this list may change.)

### Step 4. Use Pandas Datarader to read the daily time series for the Apple stock (ticker symbol AAPL) between 01/01/2015 and today, assign it to df_apple and print it.

In [4]:
!pip install --upgrade pandas-datareader

Requirement already satisfied: pandas-datareader in /usr/local/lib/python3.11/dist-packages (0.10.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (from pandas-datareader) (5.4.0)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.11/dist-packages (from pandas-datareader) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from pandas-datareader) (2.32.3)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.23->pandas-datareader) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.23->pandas-datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.23->pandas-datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.23->pandas-datareader) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->pandas-datareader) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->pandas-datareader) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->pandas-datareader) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->pandas-datareader) (2025.6.15)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas-datareader) (1.17.0)

In [5]:
!pip install yfinance --upgrade --no-cache-dir

Requirement already satisfied: yfinance in /usr/local/lib/python3.11/dist-packages (0.2.63)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.3.8)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.11/dist-packages (from yfinance) (3.18.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.13.4)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance) (0.11.4)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (5.29.5)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.14.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.11/dist-packages (from curl_cffi>=0.7->yfinance) (2025.6.15)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (2.4.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [7]:
import yfinance as yf
df_apple = yf.download('AAPL', start=start, end=end)
print(df_apple)

/tmp/ipython-input-7-319139299.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_apple = yf.download('AAPL', start=start, end=end)
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2015-01-02   24.288588   24.757342   23.848713   24.746234  212818400
2015-01-05   23.604328   24.137509   23.417716   24.057531  257142000
2015-01-06   23.606560   23.866485   23.244440   23.668764  263188400
2015-01-07   23.937569   24.037539   23.704302   23.815381  160423600
2015-01-08   24.857304   24.915065   24.148618   24.266363  237458000
...                ...         ...         ...         ...        ...
2025-06-18  196.580002  197.570007  195.070007  195.940002   45394700
2025-06-20  201.000000  201.699997  196.860001  198.240005   96813500
2025-06-23  201.500000  202.300003  198.960007  201.630005   55814300
2025-06-24  200.300003  203.440002  200.199997  202.589996   54064000
2025-06-25  201.559998  203.660004  200.620102  201.419998   37676746

[2635 rows x 5 columns]

### Step 5. Add a new column "stock" to the dataframe and add the ticker symbol

In [9]:
df_apple['stock'] = 'AAPL'
print(df_apple.head())

Price           Close       High        Low       Open     Volume stock
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2015-01-02  24.288588  24.757342  23.848713  24.746234  212818400  AAPL
2015-01-05  23.604328  24.137509  23.417716  24.057531  257142000  AAPL
2015-01-06  23.606560  23.866485  23.244440  23.668764  263188400  AAPL
2015-01-07  23.937569  24.037539  23.704302  23.815381  160423600  AAPL
2015-01-08  24.857304  24.915065  24.148618  24.266363  237458000  AAPL

### Step 6. Repeat the two previous steps for a few other stocks, always creating a new dataframe: Tesla, IBM and Microsoft. (Ticker symbols TSLA, IBM and MSFT.)

In [10]:
# Tesla
df_tesla = yf.download('TSLA', start=start, end=end)
df_tesla['stock'] = 'TSLA'

# IBM
df_ibm = yf.download('IBM', start=start, end=end)
df_ibm['stock'] = 'IBM'

# Microsoft
df_msft = yf.download('MSFT', start=start, end=end)
df_msft['stock'] = 'MSFT'

# Print sample for each
print("Apple:\n", df_apple.head(), "\n")
print("Tesla:\n", df_tesla.head(), "\n")
print("IBM:\n", df_ibm.head(), "\n")
print("Microsoft:\n", df_msft.head())

/tmp/ipython-input-10-2252651522.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_tesla = yf.download('TSLA', start=start, end=end)
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-10-2252651522.py:6: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_ibm = yf.download('IBM', start=start, end=end)
[*********************100%***********************]  1 of 1 completed
/tmp/ipython-input-10-2252651522.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_msft = yf.download('MSFT', start=start, end=end)
[*********************100%***********************]  1 of 1 completed

Apple:
 Price           Close       High        Low       Open     Volume stock
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2015-01-02  24.288588  24.757342  23.848713  24.746234  212818400  AAPL
2015-01-05  23.604328  24.137509  23.417716  24.057531  257142000  AAPL
2015-01-06  23.606560  23.866485  23.244440  23.668764  263188400  AAPL
2015-01-07  23.937569  24.037539  23.704302  23.815381  160423600  AAPL
2015-01-08  24.857304  24.915065  24.148618  24.266363  237458000  AAPL

Tesla:
 Price           Close       High        Low       Open    Volume stock
Ticker           TSLA       TSLA       TSLA       TSLA      TSLA
Date
2015-01-02  14.620667  14.883333  14.217333  14.858000  71466000  TSLA
2015-01-05  14.006000  14.433333  13.810667  14.303333  80527500  TSLA
2015-01-06  14.085333  14.280000  13.614000  14.004000  93928500  TSLA
2015-01-07  14.063333  14.318667  13.985333  14.223333  44526000  TSLA
2015-01-08  14.041333  14.253333  14.000667  14.187333  51637500  TSLA

IBM:
 Price           Close        High        Low       Open   Volume stock
Ticker            IBM         IBM        IBM        IBM      IBM
Date
2015-01-02  99.331116  100.097282  98.681414  98.871424  5779673   IBM
2015-01-05  97.768188   98.846943  97.572054  98.846943  5104898   IBM
2015-01-06  95.659714   98.044007  95.108083  97.866254  6429448   IBM
2015-01-07  95.034515   96.352312  94.409329  96.352312  4918083   IBM
2015-01-08  97.100075   97.480086  95.340969  95.763887  4431693   IBM

Microsoft:
 Price           Close       High        Low       Open    Volume stock
Ticker           MSFT       MSFT       MSFT       MSFT      MSFT
Date
2015-01-02  39.998699  40.563266  39.810512  39.913160  27913900  MSFT
2015-01-05  39.630878  39.973038  39.562445  39.665092  39673900  MSFT
2015-01-06  39.049210  39.990153  38.955115  39.673654  36447900  MSFT
2015-01-07  39.545338  39.742080  38.912340  39.331487  29114100  MSFT
2015-01-08  40.708694  40.845559  39.964494  39.990155  29645200  MSFT

### Step 7. Combine the four separate dataFrames into one combined dataFrame df that holds the information for all four stocks

In [11]:
df = pd.concat([df_apple, df_tesla, df_ibm, df_msft])
df = df.reset_index()
df.head()

Price,Date,Close,High,Low,Open,Volume,stock,Close,High,Low,...,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
Ticker,,AAPL,AAPL,AAPL,AAPL,AAPL,,TSLA,TSLA,TSLA,...,IBM,IBM,IBM,IBM,IBM,MSFT,MSFT,MSFT,MSFT,MSFT
0,2015-01-02,24.288588,24.757342,23.848713,24.746234,212818400.0,AAPL,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-01-05,23.604328,24.137509,23.417716,24.057531,257142000.0,AAPL,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-01-06,23.606560,23.866485,23.244440,23.668764,263188400.0,AAPL,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-01-07,23.937569,24.037539,23.704302,23.815381,160423600.0,AAPL,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-01-08,24.857304,24.915065,24.148618,24.266363,237458000.0,AAPL,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 8. Shift the stock column into the index (making it a multi-level index consisting of the ticker symbol and the date).

In [15]:
df['Date'] = pd.to_datetime(df['Date'])  # Just to be safe
df = df.set_index(['stock', 'Date'])

print(df.head())

Price                 Close       High        Low       Open       Volume  \
Ticker                 AAPL       AAPL       AAPL       AAPL         AAPL
stock Date
AAPL  2015-01-02  24.288588  24.757342  23.848713  24.746234  212818400.0
      2015-01-05  23.604328  24.137509  23.417716  24.057531  257142000.0
      2015-01-06  23.606560  23.866485  23.244440  23.668764  263188400.0
      2015-01-07  23.937569  24.037539  23.704302  23.815381  160423600.0
      2015-01-08  24.857304  24.915065  24.148618  24.266363  237458000.0

Price            Close High  Low Open Volume Close High Low Open Volume Close  \
Ticker            TSLA TSLA TSLA TSLA   TSLA   IBM  IBM IBM  IBM    IBM  MSFT
stock Date
AAPL  2015-01-02   NaN  NaN  NaN  NaN    NaN   NaN  NaN NaN  NaN    NaN   NaN
      2015-01-05   NaN  NaN  NaN  NaN    NaN   NaN  NaN NaN  NaN    NaN   NaN
      2015-01-06   NaN  NaN  NaN  NaN    NaN   NaN  NaN NaN  NaN    NaN   NaN
      2015-01-07   NaN  NaN  NaN  NaN    NaN   NaN  NaN NaN  NaN    NaN   NaN
      2015-01-08   NaN  NaN  NaN  NaN    NaN   NaN  NaN NaN  NaN    NaN   NaN

Price            High  Low Open Volume
Ticker           MSFT MSFT MSFT   MSFT
stock Date
AAPL  2015-01-02  NaN  NaN  NaN    NaN
      2015-01-05  NaN  NaN  NaN    NaN
      2015-01-06  NaN  NaN  NaN    NaN
      2015-01-07  NaN  NaN  NaN    NaN
      2015-01-08  NaN  NaN  NaN    NaN

### Step 7. Create a dataFrame called vol, with the volume values.

In [14]:
vol = df.Volume
vol.head()

Ticker         AAPL  TSLA  IBM  MSFT
0       212818400.0   NaN  NaN   NaN
1       257142000.0   NaN  NaN   NaN
2       263188400.0   NaN  NaN   NaN
3       160423600.0   NaN  NaN   NaN
4       237458000.0   NaN  NaN   NaN

### Step 8. Aggregate the data of volume to weekly.
Hint: Be careful to not sum data from the same week of 2015 and other years.

In [ ]:
weekly_vol = vol.groupby(level='stock').resample('W', level='Date').sum()

print(weekly_vol.head(10))

### Step 9. Find all the volume traded in the year of 2015

In [ ]:
# Step 1: Filter for 2015 using the Date level in the MultiIndex
volume_2015 = df.loc[(slice(None), slice('2015-01-01', '2015-12-31')), 'Volume']

# Step 2: Group by 'stock' and sum
total_volume_2015 = volume_2015.groupby(level='stock').sum()

print(total_volume_2015)